/**
 * Nifty 500 constituent list for autocomplete in the profile watchlist.
 * Detailed list of top constituents across all 12 key sectors.
 */
export const NIFTY_500 = [
  // ── BANKING & FINANCE ──
  { ticker: 'HDFCBANK', name: 'HDFC Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'ICICIBANK', name: 'ICICI Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'SBIN', name: 'State Bank of India', sector: 'Banking & Finance' },
  { ticker: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'AXISBANK', name: 'Axis Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'INDUSINDBK', name: 'IndusInd Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'BANKBARODA', name: 'Bank of Baroda', sector: 'Banking & Finance' },
  { ticker: 'PNB', name: 'Punjab National Bank', sector: 'Banking & Finance' },
  { ticker: 'CANBK', name: 'Canara Bank', sector: 'Banking & Finance' },
  { ticker: 'UNIONBANK', name: 'Union Bank of India', sector: 'Banking & Finance' },
  { ticker: 'INDIANB', name: 'Indian Bank', sector: 'Banking & Finance' },
  { ticker: 'UCOBANK', name: 'UCO Bank', sector: 'Banking & Finance' },
  { ticker: 'CENTRALBK', name: 'Central Bank of India', sector: 'Banking & Finance' },
  { ticker: 'IOB', name: 'Indian Overseas Bank', sector: 'Banking & Finance' },
  { ticker: 'YESBANK', name: 'Yes Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'IDFCFIRSTB', name: 'IDFC First Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'FEDERALBNK', name: 'Federal Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'BANDHANBNK', name: 'Bandhan Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'KARURVYSYA', name: 'Karur Vysya Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'CUB', name: 'City Union Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'RBLBANK', name: 'RBL Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'AUBANK', name: 'AU Small Finance Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'UJJIVANSFB', name: 'Ujjivan Small Finance Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'EQUITASBNK', name: 'Equitas Small Finance Bank Ltd', sector: 'Banking & Finance' },
  { ticker: 'BAJFINANCE', name: 'Bajaj Finance Ltd', sector: 'Banking & Finance' },
  { ticker: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd', sector: 'Banking & Finance' },
  { ticker: 'CHOLAFIN', name: 'Cholamandalam Investment & Finance', sector: 'Banking & Finance' },
  { ticker: 'MUTHOOTFIN', name: 'Muthoot Finance Ltd', sector: 'Banking & Finance' },
  { ticker: 'RECLTD', name: 'REC Ltd', sector: 'Banking & Finance' },
  { ticker: 'PFC', name: 'Power Finance Corporation Ltd', sector: 'Banking & Finance' },
  { ticker: 'SHRIRAMFIN', name: 'Shriram Finance Ltd', sector: 'Banking & Finance' },
  { ticker: 'L&TFH', name: 'L&T Finance Holdings Ltd', sector: 'Banking & Finance' },
  { ticker: 'M&MFIN', name: 'Mahindra & Mahindra Financial Services', sector: 'Banking & Finance' },
  { ticker: 'POONAWALLA', name: 'Poonawalla Fincorp Ltd', sector: 'Banking & Finance' },
  { ticker: 'HDFCLIFE', name: 'HDFC Life Insurance Co Ltd', sector: 'Banking & Finance' },
  { ticker: 'SBILIFE', name: 'SBI Life Insurance Co Ltd', sector: 'Banking & Finance' },
  { ticker: 'ICICIPRULI', name: 'ICICI Prudential Life Insurance', sector: 'Banking & Finance' },
  { ticker: 'LICHSGFIN', name: 'LIC Housing Finance Ltd', sector: 'Banking & Finance' },
  { ticker: 'HUDCO', name: 'Housing & Urban Development Corp', sector: 'Banking & Finance' },
  { ticker: 'GICRE', name: 'General Insurance Corporation of India', sector: 'Banking & Finance' },
  { ticker: 'NIACL', name: 'New India Assurance Co Ltd', sector: 'Banking & Finance' },
  { ticker: 'MANAPPURAM', name: 'Manappuram Finance Ltd', sector: 'Banking & Finance' },
  { ticker: 'IBULHSGFIN', name: 'Indiabulls Housing Finance Ltd', sector: 'Banking & Finance' },
  { ticker: 'ANGELONE', name: 'Angel One Ltd', sector: 'Banking & Finance' },
  { ticker: 'CDSL', name: 'Central Depository Services (India) Ltd', sector: 'Banking & Finance' },
  { ticker: 'MCX', name: 'Multi Commodity Exchange of India Ltd', sector: 'Banking & Finance' },

  // ── INFORMATION TECHNOLOGY ──
  { ticker: 'TCS', name: 'Tata Consultancy Services Ltd', sector: 'Information Technology' },
  { ticker: 'INFY', name: 'Infosys Ltd', sector: 'Information Technology' },
  { ticker: 'HCLTECH', name: 'HCL Technologies Ltd', sector: 'Information Technology' },
  { ticker: 'WIPRO', name: 'Wipro Ltd', sector: 'Information Technology' },
  { ticker: 'TECHM', name: 'Tech Mahindra Ltd', sector: 'Information Technology' },
  { ticker: 'LTIM', name: 'LTIMindtree Ltd', sector: 'Information Technology' },
  { ticker: 'LTTS', name: 'L&T Technology Services Ltd', sector: 'Information Technology' },
  { ticker: 'MPHASIS', name: 'Mphasis Ltd', sector: 'Information Technology' },
  { ticker: 'PERSISTENT', name: 'Persistent Systems Ltd', sector: 'Information Technology' },
  { ticker: 'COFORGE', name: 'Coforge Ltd', sector: 'Information Technology' },
  { ticker: 'KPITTECH', name: 'KPIT Technologies Ltd', sector: 'Information Technology' },
  { ticker: 'TATAELXSI', name: 'Tata Elxsi Ltd', sector: 'Information Technology' },
  { ticker: 'CYIENT', name: 'Cyient Ltd', sector: 'Information Technology' },
  { ticker: 'BSOFT', name: 'BirlaSoft Ltd', sector: 'Information Technology' },
  { ticker: 'OFSS', name: 'Oracle Financial Services Software', sector: 'Information Technology' },
  { ticker: 'SONATSOFTW', name: 'Sonata Software Ltd', sector: 'Information Technology' },
  { ticker: 'ZENSARTECH', name: 'Zensar Technologies Ltd', sector: 'Information Technology' },
  { ticker: 'INTELLECT', name: 'Intellect Design Arena Ltd', sector: 'Information Technology' },
  { ticker: 'NEWGEN', name: 'Newgen Software Technologies Ltd', sector: 'Information Technology' },
  { ticker: 'AFFLE', name: 'Affle (India) Ltd', sector: 'Information Technology' },
  { ticker: 'ROUTE', name: 'Route Mobile Ltd', sector: 'Information Technology' },
  { ticker: 'ZOMATO', name: 'Zomato Ltd', sector: 'Information Technology' },
  { ticker: 'CEINFO', name: 'C.E. Info Systems Ltd (MapmyIndia)', sector: 'Information Technology' },
  { ticker: 'MASTEK', name: 'Mastek Ltd', sector: 'Information Technology' },

  // ── ENERGY ──
  { ticker: 'RELIANCE', name: 'Reliance Industries Ltd', sector: 'Energy' },
  { ticker: 'ONGC', name: 'Oil & Natural Gas Corporation Ltd', sector: 'Energy' },
  { ticker: 'IOC', name: 'Indian Oil Corporation Ltd', sector: 'Energy' },
  { ticker: 'BPCL', name: 'Bharat Petroleum Corporation Ltd', sector: 'Energy' },
  { ticker: 'HPCL', name: 'Hindustan Petroleum Corporation Ltd', sector: 'Energy' },
  { ticker: 'POWERGRID', name: 'Power Grid Corporation of India Ltd', sector: 'Energy' },
  { ticker: 'NTPC', name: 'NTPC Ltd', sector: 'Energy' },
  { ticker: 'ADANIGREEN', name: 'Adani Green Energy Ltd', sector: 'Energy' },
  { ticker: 'TATAPOWER', name: 'Tata Power Company Ltd', sector: 'Energy' },
  { ticker: 'NHPC', name: 'NHPC Ltd', sector: 'Energy' },
  { ticker: 'SJVN', name: 'SJVN Ltd', sector: 'Energy' },
  { ticker: 'GAIL', name: 'GAIL (India) Ltd', sector: 'Energy' },
  { ticker: 'IGL', name: 'Indraprastha Gas Ltd', sector: 'Energy' },
  { ticker: 'MGL', name: 'Mahanagar Gas Ltd', sector: 'Energy' },
  { ticker: 'GUJGASLTD', name: 'Gujarat Gas Ltd', sector: 'Energy' },
  { ticker: 'GSPL', name: 'Gujarat State Petronet Ltd', sector: 'Energy' },
  { ticker: 'PETRONET', name: 'Petronet LNG Ltd', sector: 'Energy' },
  { ticker: 'ADANIPOWER', name: 'Adani Power Ltd', sector: 'Energy' },
  { ticker: 'ADANIENSOL', name: 'Adani Energy Solutions Ltd', sector: 'Energy' },
  { ticker: 'CESC', name: 'CESC Ltd', sector: 'Energy' },
  { ticker: 'JSWENERGY', name: 'JSW Energy Ltd', sector: 'Energy' },
  { ticker: 'TORNTPOWER', name: 'Torrent Power Ltd', sector: 'Energy' },
  { ticker: 'OIL', name: 'Oil India Ltd', sector: 'Energy' },
  { ticker: 'MRPL', name: 'Mangalore Refinery & Petrochemicals', sector: 'Energy' },

  // ── PHARMACEUTICALS ──
  { ticker: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'DRREDDY', name: "Dr. Reddy's Laboratories Ltd", sector: 'Pharmaceuticals' },
  { ticker: 'CIPLA', name: 'Cipla Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'DIVISLAB', name: "Divi's Laboratories Ltd", sector: 'Pharmaceuticals' },
  { ticker: 'BIOCON', name: 'Biocon Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'AUROPHARMA', name: 'Aurobindo Pharma Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'LUPIN', name: 'Lupin Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'TORNTPHARM', name: 'Torrent Pharmaceuticals Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'ABBOTINDIA', name: 'Abbott India Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'ALKEM', name: 'Alkem Laboratories Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'IPCALAB', name: 'IPCA Laboratories Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'GLAND', name: 'Gland Pharma Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'LAURUSLABS', name: 'Laurus Labs Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'GRANULES', name: 'Granules India Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'JBCHEPHARM', name: 'J.B. Chemicals & Pharmaceuticals', sector: 'Pharmaceuticals' },
  { ticker: 'GLENMARK', name: 'Glenmark Pharmaceuticals Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'ZYDUSLIFE', name: 'Zydus Lifesciences Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'ERIS', name: 'Eris Lifesciences Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'SYNGENE', name: 'Syngene International Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'NATCOPHARM', name: 'Natco Pharma Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'GLAXO', name: 'GlaxoSmithKline Pharmaceuticals', sector: 'Pharmaceuticals' },
  { ticker: 'SANOFI', name: 'Sanofi India Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'CONCORDBIO', name: 'Concord Biotech Ltd', sector: 'Pharmaceuticals' },
  { ticker: 'PIRAMALPHY', name: 'Piramal Pharma Ltd', sector: 'Pharmaceuticals' },

  // ── FMCG ──
  { ticker: 'HINDUNILVR', name: 'Hindustan Unilever Ltd', sector: 'FMCG' },
  { ticker: 'ITC', name: 'ITC Ltd', sector: 'FMCG' },
  { ticker: 'NESTLEIND', name: 'Nestle India Ltd', sector: 'FMCG' },
  { ticker: 'BRITANNIA', name: 'Britannia Industries Ltd', sector: 'FMCG' },
  { ticker: 'DABUR', name: 'Dabur India Ltd', sector: 'FMCG' },
  { ticker: 'MARICO', name: 'Marico Ltd', sector: 'FMCG' },
  { ticker: 'COLPAL', name: 'Colgate-Palmolive (India) Ltd', sector: 'FMCG' },
  { ticker: 'GODREJCP', name: 'Godrej Consumer Products Ltd', sector: 'FMCG' },
  { ticker: 'TATACONSUM', name: 'Tata Consumer Products Ltd', sector: 'FMCG' },
  { ticker: 'VBL', name: 'Varun Beverages Ltd', sector: 'FMCG' },
  { ticker: 'BALRAMCHIN', name: 'Balrampur Chini Mills Ltd', sector: 'FMCG' },
  { ticker: 'RENUKA', name: 'Shree Renuka Sugars Ltd', sector: 'FMCG' },
  { ticker: 'RADICO', name: 'Radico Khaitan Ltd', sector: 'FMCG' },
  { ticker: 'MCDOWELL-N', name: 'United Spirits Ltd (McDowell)', sector: 'FMCG' },
  { ticker: 'EMAMILTD', name: 'Emami Ltd', sector: 'FMCG' },
  { ticker: 'JYOTHYLAB', name: 'Jyothy Labs Ltd', sector: 'FMCG' },
  { ticker: 'KRBL', name: 'KRBL Ltd', sector: 'FMCG' },
  { ticker: 'BECTORFOOD', name: 'Mrs. Bectors Food Specialities', sector: 'FMCG' },
  { ticker: 'LTFOODS', name: 'LT Foods Ltd', sector: 'FMCG' },
  { ticker: 'HATSUN', name: 'Hatsun Agro Product Ltd', sector: 'FMCG' },
  { ticker: 'TASTYBITE', name: 'Tasty Bite Eatables Ltd', sector: 'FMCG' },

  // ── TELECOM ──
  { ticker: 'BHARTIARTL', name: 'Bharti Airtel Ltd', sector: 'Telecom' },
  { ticker: 'VODAFONE', name: 'Vodafone Idea Ltd', sector: 'Telecom' },
  { ticker: 'INDUSTOWER', name: 'Indus Towers Ltd', sector: 'Telecom' },
  { ticker: 'TATACOMM', name: 'Tata Communications Ltd', sector: 'Telecom' },
  { ticker: 'TEJASNET', name: 'Tejas Networks Ltd', sector: 'Telecom' },
  { ticker: 'HFCL', name: 'HFCL Ltd', sector: 'Telecom' },

  // ── AUTOMOBILE ──
  { ticker: 'MARUTI', name: 'Maruti Suzuki India Ltd', sector: 'Automobile' },
  { ticker: 'TATAMOTORS', name: 'Tata Motors Ltd', sector: 'Automobile' },
  { ticker: 'M&M', name: 'Mahindra & Mahindra Ltd', sector: 'Automobile' },
  { ticker: 'BAJAJ-AUTO', name: 'Bajaj Auto Ltd', sector: 'Automobile' },
  { ticker: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd', sector: 'Automobile' },
  { ticker: 'EICHERMOT', name: 'Eicher Motors Ltd', sector: 'Automobile' },
  { ticker: 'TVSMOTOR', name: 'TVS Motor Company Ltd', sector: 'Automobile' },
  { ticker: 'ASHOKLEY', name: 'Ashok Leyland Ltd', sector: 'Automobile' },
  { ticker: 'BALKRISIND', name: 'Balkrishna Industries Ltd', sector: 'Automobile' },
  { ticker: 'MRF', name: 'MRF Ltd', sector: 'Automobile' },
  { ticker: 'APOLLOTYRE', name: 'Apollo Tyres Ltd', sector: 'Automobile' },
  { ticker: 'CEATLTD', name: 'CEAT Ltd', sector: 'Automobile' },
  { ticker: 'MOTHERSON', name: 'Samvardhana Motherson International', sector: 'Automobile' },
  { ticker: 'BOSCHLTD', name: 'Bosch Ltd', sector: 'Automobile' },
  { ticker: 'ENDURANCE', name: 'Endurance Technologies Ltd', sector: 'Automobile' },
  { ticker: 'SUPRAJIT', name: 'Suprajit Engineering Ltd', sector: 'Automobile' },
  { ticker: 'UNOMINDA', name: 'Uno Minda Ltd', sector: 'Automobile' },
  { ticker: 'EXIDEIND', name: 'Exide Industries Ltd', sector: 'Automobile' },
  { ticker: 'AMARAJABAT', name: 'Amara Raja Energy & Mobility Ltd', sector: 'Automobile' },
  { ticker: 'ESCORTS', name: 'Escorts Kubota Ltd', sector: 'Automobile' },
  { ticker: 'SONACOMS', name: 'Sona BLW Precision Forgings Ltd', sector: 'Automobile' },
  { ticker: 'TUBEINVEST', name: 'Tube Investments of India Ltd', sector: 'Automobile' },
  { ticker: 'CRAFTSMAN', name: 'Craftsman Automation Ltd', sector: 'Automobile' },

  // ── METALS & MINING ──
  { ticker: 'TATASTEEL', name: 'Tata Steel Ltd', sector: 'Metals & Mining' },
  { ticker: 'JSWSTEEL', name: 'JSW Steel Ltd', sector: 'Metals & Mining' },
  { ticker: 'HINDALCO', name: 'Hindalco Industries Ltd', sector: 'Metals & Mining' },
  { ticker: 'VEDL', name: 'Vedanta Ltd', sector: 'Metals & Mining' },
  { ticker: 'COALINDIA', name: 'Coal India Ltd', sector: 'Metals & Mining' },
  { ticker: 'NMDC', name: 'NMDC Ltd', sector: 'Metals & Mining' },
  { ticker: 'SAIL', name: 'Steel Authority of India Ltd', sector: 'Metals & Mining' },
  { ticker: 'JINDALSTEL', name: 'Jindal Steel & Power Ltd', sector: 'Metals & Mining' },
  { ticker: 'NATIONALUM', name: 'National Aluminium Co Ltd', sector: 'Metals & Mining' },
  { ticker: 'HINDZINC', name: 'Hindustan Zinc Ltd', sector: 'Metals & Mining' },
  { ticker: 'APLAPOLLO', name: 'APL Apollo Tubes Ltd', sector: 'Metals & Mining' },
  { ticker: 'WELCORP', name: 'Welspun Corp Ltd', sector: 'Metals & Mining' },
  { ticker: 'RATNAMANI', name: 'Ratnamani Metals & Tubes Ltd', sector: 'Metals & Mining' },
  { ticker: 'HINDCOPPER', name: 'Hindustan Copper Ltd', sector: 'Metals & Mining' },
  { ticker: 'GPIL', name: 'Godawari Power & Ispat Ltd', sector: 'Metals & Mining' },
  { ticker: 'JSL', name: 'Jindal Stainless Ltd', sector: 'Metals & Mining' },

  // ── CAPITAL GOODS ──
  { ticker: 'LT', name: 'Larsen & Toubro Ltd', sector: 'Capital Goods' },
  { ticker: 'SIEMENS', name: 'Siemens Ltd', sector: 'Capital Goods' },
  { ticker: 'ABB', name: 'ABB India Ltd', sector: 'Capital Goods' },
  { ticker: 'BHEL', name: 'Bharat Heavy Electricals Ltd', sector: 'Capital Goods' },
  { ticker: 'HAVELLS', name: 'Havells India Ltd', sector: 'Capital Goods' },
  { ticker: 'POLYCAB', name: 'Polycab India Ltd', sector: 'Capital Goods' },
  { ticker: 'KEI', name: 'KEI Industries Ltd', sector: 'Capital Goods' },
  { ticker: 'CGPOWER', name: 'CG Power & Industrial Solutions Ltd', sector: 'Capital Goods' },
  { ticker: 'BEL', name: 'Bharat Electronics Ltd', sector: 'Capital Goods' },
  { ticker: 'HAL', name: 'Hindustan Aeronautics Ltd', sector: 'Capital Goods' },
  { ticker: 'MAZDOCK', name: 'Mazagon Dock Shipbuilders Ltd', sector: 'Capital Goods' },
  { ticker: 'GRSE', name: 'Garden Reach Shipbuilders & Engineers', sector: 'Capital Goods' },
  { ticker: 'BDL', name: 'Bharat Dynamics Ltd', sector: 'Capital Goods' },
  { ticker: 'CUMMINSIND', name: 'Cummins India Ltd', sector: 'Capital Goods' },
  { ticker: 'THERMAX', name: 'Thermax Ltd', sector: 'Capital Goods' },
  { ticker: 'KIRLOSENG', name: 'Kirloskar Oil Engines Ltd', sector: 'Capital Goods' },
  { ticker: 'VOLTAS', name: 'Voltas Ltd', sector: 'Capital Goods' },
  { ticker: 'BLUESTARCO', name: 'Blue Star Ltd', sector: 'Capital Goods' },
  { ticker: 'DIXON', name: 'Dixon Technologies (India) Ltd', sector: 'Capital Goods' },
  { ticker: 'KAYNES', name: 'Kaynes Technology India Ltd', sector: 'Capital Goods' },
  { ticker: 'AMBER', name: 'Amber Enterprises India Ltd', sector: 'Capital Goods' },
  { ticker: 'TRITURBINE', name: 'Triveni Turbine Ltd', sector: 'Capital Goods' },
  { ticker: 'AIAENG', name: 'AIA Engineering Ltd', sector: 'Capital Goods' },
  { ticker: 'CARBORUNIV', name: 'Carborundum Universal Ltd', sector: 'Capital Goods' },
  { ticker: 'ELGIEQUIP', name: 'Elgi Equipments Ltd', sector: 'Capital Goods' },
  { ticker: 'HECS', name: 'Hindustan Construction Company Ltd', sector: 'Capital Goods' },
  { ticker: 'IRR', name: 'IRCON International Ltd', sector: 'Capital Goods' },
  { ticker: 'RVNL', name: 'Rail Vikas Nigam Ltd', sector: 'Capital Goods' },
  { ticker: 'RITES', name: 'RITES Ltd', sector: 'Capital Goods' },
  { ticker: 'RAILTEL', name: 'RailTel Corporation of India Ltd', sector: 'Capital Goods' },
  { ticker: 'CONCOR', name: 'Container Corporation of India Ltd', sector: 'Capital Goods' },
  { ticker: 'GPPL', name: 'Gujarat Pipavav Port Ltd', sector: 'Capital Goods' },

  // ── REAL ESTATE & CEMENTS ──
  { ticker: 'DLF', name: 'DLF Ltd', sector: 'Real Estate' },
  { ticker: 'GODREJPROP', name: 'Godrej Properties Ltd', sector: 'Real Estate' },
  { ticker: 'OBEROIRLTY', name: 'Oberoi Realty Ltd', sector: 'Real Estate' },
  { ticker: 'PRESTIGE', name: 'Prestige Estates Projects Ltd', sector: 'Real Estate' },
  { ticker: 'SOBHA', name: 'Sobha Ltd', sector: 'Real Estate' },
  { ticker: 'SUNTECK', name: 'Sunteck Realty Ltd', sector: 'Real Estate' },
  { ticker: 'BRIGADE', name: 'Brigade Enterprises Ltd', sector: 'Real Estate' },
  { ticker: 'ULTRACEMCO', name: 'UltraTech Cement Ltd', sector: 'Real Estate' },
  { ticker: 'SHREECEM', name: 'Shree Cement Ltd', sector: 'Real Estate' },
  { ticker: 'AMBUJACEM', name: 'Ambuja Cements Ltd', sector: 'Real Estate' },
  { ticker: 'ACC', name: 'ACC Ltd', sector: 'Real Estate' },
  { ticker: 'RAMCOCEM', name: 'The Ramco Cements Ltd', sector: 'Real Estate' },
  { ticker: 'DALBHARAT', name: 'Dalmia Bharat Ltd', sector: 'Real Estate' },
  { ticker: 'JKCEMENT', name: 'JK Cement Ltd', sector: 'Real Estate' },
  { ticker: 'INDIACEM', name: 'The India Cements Ltd', sector: 'Real Estate' },
  { ticker: 'PRISMJOHNS', name: 'Prism Johnson Ltd', sector: 'Real Estate' },

  // ── CONSUMER DISCRETIONARY ──
  { ticker: 'TITAN', name: 'Titan Company Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'ASIANPAINT', name: 'Asian Paints Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'BERGEPAINT', name: 'Berger Paints India Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'KANSAINER', name: 'Kansai Nerolac Paints Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'PIDILITIND', name: 'Pidilite Industries Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'TRENT', name: 'Trent Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'NYKAA', name: 'FSN E-Commerce Ventures Ltd (Nykaa)', sector: 'Consumer Discretionary' },
  { ticker: 'DMART', name: 'Avenue Supermarts Ltd (D-Mart)', sector: 'Consumer Discretionary' },
  { ticker: 'PAGEIND', name: 'Page Industries Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'BATAINDIA', name: 'Bata India Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'RELAXO', name: 'Relaxo Footwears Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'METROBRAND', name: 'Metro Brands Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'ABFRL', name: 'Aditya Birla Fashion & Retail Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'VMART', name: 'V-Mart Retail Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'SAFARI', name: 'Safari Industries (India) Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'VIPIND', name: 'VIP Industries Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'KALYANKJIL', name: 'Kalyan Jewellers India Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'SENCO', name: 'Senco Gold Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'ETHOSLTD', name: 'Ethos Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'DEVYANI', name: 'Devyani International Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'JUBILANT', name: 'Jubilant FoodWorks Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'WESTLIFE', name: 'Westlife Foodworld Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'RESTAUTEN', name: 'Restaurant Brands Asia Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'PVRINOX', name: 'PVR Inox Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'SUNTV', name: 'Sun TV Network Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'ZEEL', name: 'Zee Entertainment Enterprises Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'DISHTV', name: 'Dish TV India Ltd', sector: 'Consumer Discretionary' },
  { ticker: 'NAUKRI', name: 'Info Edge (India) Ltd (Naukri.com)', sector: 'Consumer Discretionary' },

  // ── HEALTHCARE ──
  { ticker: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise Ltd', sector: 'Healthcare' },
  { ticker: 'MAXHEALTH', name: 'Max Healthcare Institute Ltd', sector: 'Healthcare' },
  { ticker: 'FORTIS', name: 'Fortis Healthcare Ltd', sector: 'Healthcare' },
  { ticker: 'NH', name: 'Narayana Hrudayalaya Ltd', sector: 'Healthcare' },
  { ticker: 'MEDANTA', name: 'Global Health Ltd (Medanta)', sector: 'Healthcare' },
  { ticker: 'ASTERDM', name: 'Aster DM Healthcare Ltd', sector: 'Healthcare' },
  { ticker: 'LALPATHLAB', name: 'Dr. Lal PathLabs Ltd', sector: 'Healthcare' },
  { ticker: 'METROPOLIS', name: 'Metropolis Healthcare Ltd', sector: 'Healthcare' },
  { ticker: 'ZYDUSWELL', name: 'Zydus Wellness Ltd', sector: 'Healthcare' },
  { ticker: 'RAINBOW', name: "Rainbow Children's Medicare Ltd", sector: 'Healthcare' },
  { ticker: 'SHALBY', name: 'Shalby Ltd', sector: 'Healthcare' },
  { ticker: 'VIJAYA', name: 'Vijaya Diagnostic Centre Ltd', sector: 'Healthcare' },
  { ticker: 'BLUEJET', name: 'Blue Jet Healthcare Ltd', sector: 'Healthcare' },
]

export const SECTORS = [
  'Banking & Finance',
  'Information Technology',
  'Energy',
  'Pharmaceuticals',
  'FMCG',
  'Telecom',
  'Automobile',
  'Metals & Mining',
  'Capital Goods',
  'Real Estate',
  'Consumer Discretionary',
  'Healthcare',
]

export const EVENT_CATEGORIES = [
  'Earnings',
  'Corporate Action',
  'Regulatory',
  'M&A',
  'Business Expansion',
  'Business Deterioration',
  'Legal',
  'Macro',
  'Sector',
  'Global',
]

/**
 * Search Nifty 500 list by name or ticker.
 * @param {string} query
 * @returns {Array}
 */
export function searchNifty500(query) {
  if (!query || query.length < 1) return []
  const q = query.toLowerCase()
  return NIFTY_500.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.ticker.toLowerCase().includes(q) ||
      s.sector.toLowerCase().includes(q)
  ).slice(0, 10)
}
